#-------------------------------
# Site Settings
title: Yudhanjaya
#logo: '/images/icon.png'
description: Portfolio, links, contact details and more for Yudhanjaya Wijeratne.
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.
#Abandon all hope, ye who enter here - Lasciate ogne speranza, voi ch'intrate - just keep changin

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Books'
      url: '/book/'
    - title: 'Software'
      url: '/software/'
    - title: 'Projects'
      url: '/project/'
    - title: 'Essays and updates'
      url: '/essays/'
    - title: 'Notes and errata'
      url: '/note/'

#-------------------------------
# Author Settings
author:
  author__name: Yudhanjaya Wijeratne
  author__bio: To get in touch, reach out to hello [at] yudhanjaya [dot] com, or contact fingan [at] zenoagency [dot] com to talk to my agent.  Responses from my end may take time. 
  author__avatar: '/images/icon2.png'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Hi. I'm Yudhanjaya Wijeratne.
  hero__description: I'm a storyteller from Colombo, Sri Lanka. I show up in many different guises - an award-winning author, OSINT journalist, data scientist, occasional game designer and AI programmer. Welcome to my portfolio and digital garden.
  hero__image: '/images/yudha.jpg'


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: I’ve been featured in some interesting places. 

logo__items:
  - name: Google Research
    link: "https://arxiv.org/pdf/2211.05030.pdf"
    image: "/images/google.svg"

  - name: The New York Times
    link: "https://www.nytimes.com/interactive/2023/06/01/opinion/ai-technology-future.html"
    image: "/images/NewYorkTimes.svg"

  - name: Rest of World
    link: "https://restofworld.org/2022/meet-the-fact-checkers-decoding-sri-lankas-meltdown/"
    image: "/images/row.svg"

  - name: Foreign Policy
    link: "https://foreignpolicy.com/2019/05/07/big-tech-is-as-monolingual-as-americans/"
    image: "/images/foreignpolicy.png"

  - name: Wired
    link: "https://www.wired.com/story/future-of-work-work-ethics-yudhanjaya-wijeratne/"
    image: "/images/wired.svg"

  - name: Himal Southasian
    link: "https://www.himalmag.com/contemporary-speculative-fiction-fantasy-sri-lanka/"
    image: "/images/himal.svg"

  - name: Forbes
    link: "https://www.forbes.com/profile/yudhanjaya-wijeratne/?sh=4d316db0173a"
    image: "/images/forbes.png"

#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Subscribe


#-------------------------------
# Books Settings
book:
  enable: true
  book__title: Books!
  book__description: My stories have won the Gratiean Prize, been nominated for the Nebula and Independent Games Festival awards, appeared in venues like Wired, ForeignPolicy and Slate, and been Washington Post and Audible bestsellers. These are my biggest, publicly accessible works.  

#-------------------------------
# notes Settings
note:
  enable: false
  note__title: Notes and errata
  note__description: Various notes and frontmatter from my books. 

#-------------------------------
# essays Settings
essay:
  enable: false
  note__title: Essays and updates
  note__description: I write about a lot of things - technology, science fiction, the future, and my own experiences with them. Not all of them make it out alive past my inner critic. This is where I park the survivors.

#-------------------------------
# Projects
project:
  enable: true
  project__title: Special Projects
  project__description: I’m usually working on several things at any given time. Sometimes these are tiny projects - sometimes they’re long, perpetual, possibly Sisyphean acts of tomfoolery. This is what I’m working on right now.

#-------------------------------
# software Settings
software:
  enable: true
  software__title: Software
  software__description: I speak to the machine often, and from time to time I produce something that might be interesting. Here's a few of them.

#-------------------------------
# Testimonials Section
testimonials:
  enable: false

testimonial__title: Institutions
testimonial__description: I've worked at or with a number of very interesting organizations, including 

testimonial__items:
  - name: "Watchdog"
    image: "/images/institutions/1.png"
    designation: "Cofounder + CEO + Editor in Chief"
    link: "https://watchdog.team"
    content: "Watchdog is a multidisciplinary team of journalists, researchers and software engineers. We began in April 2019, days after the Easter Sunday bombings in Sri Lanka, building a mobile app that was used by over 200,000 people to verify information and counteract rumors in their own networks. We've since moved on to identifying mass graves, doing deep data dives into public infrastructure, and building open-source software now used by the Ministry of Health and Red Cross Sri Lanka. We use a lot of OSINT techniques - a combination of data scraping, analysis of publicly available documents and datasets, paired with old-school boots-on-the-ground journalism."

  - name: "The Dangerous Speech Project"
    image: "/images/institutions/2.png"
    designation: "Research Fellow"
    link: "https://dangerousspeech.org"
    content : "As a fellow for the Dangerous Speech Project, I collected datasets and studied ethnic hatred and justifications of war crimes centered around the Sri Lankan Civil War, as well as the historical context that led up to it."

  - name: "CoFutures, University of Oslo"
    image: "/images/institutions/3.png"
    designation: "Creator, MOOC"
    link: "https://cofutures.org"
    content : "Developing a syllabus and materials on how to write and develop SFF, with examples and lessons from around the world."

  - name: "Sci-Fi Economics Lab"
    image: "/images/institutions/4.png"
    designation: "Architect"
    link: "https://witness.scifieconomicslab.net"
    content : "I functioned as lead designer and writer of Project Witness, an open-source climate-addled future exploring alternate economic structures and their societies. Working with the very multi-disciplinary folks over at Edgeryders, I co-designed societies, built religions, fleshed out institutions, interactions and lore, and built a card game where different types of societies react to Black Swan events. Because of the team, and the sheer variety and depth and understanding of very different economic principles that they held, I came away with a lot more knowledge than I walked in with."

  - name: "LIRNEasia"
    image: "/images/institutions/5.png"
    designation: "Senior Researcher, Big Data For Development"
    link: "https://lirneasia.net/"
    content : "Our unit was centered on data science x public policy in the Global South - things like using millions of call detail records to identify where we need better road infrastructure. My work included grounded futurisms, examinations of digital laws, and academic work on corpus linguistics, social networks and machine learning, occasionally carrying out research collaborations with the University of Moratuwa. It greatly honed my understanding of the world and my technical skills, esepcially around linguistics; the majority of outputs from this time are easily available via Google Scholar."

  - name: "WSO2"
    image: "/images/institutions/6.png"
    designation: "Marketing exec, Big Data neophyte"
    link: "https://wso2.com/"
    content : "At WSO2 I worked on marketing materials and white papers of middleware implementations. These included projects with folks ranging from Transport for London to the Govt of Maldova. Later, I worked on data projects such as the WSO2 Election Monitor, from design to prototyping to implementation. This was where I got into data science proper."

 # - name: "Readme.lk"
 #   image: "/images/institutions/7.png"
 #   designation: "Founding Editor"
 #   link: "https://readme.lk/"
 #   content : "Sri Lanka's oldest consistent tech news hub. Undertook daily content as well as harder-hitting investigations, built a team, and had a whale of a time,"

 

#-------------------------------
# Blog Section
blog:
  enable: false
blog__settings:
  blog__title: Essays and updates
  blog__description:  I write about a lot of things - technology, science fiction, the future, and my own experiences with them. Not all of them make it out alive past my inner critic. This is where I park the survivors.    

#-------------------------------
# Footer Settings
#footer__background__image: "/images/bg.jpg"

#-------------------------------
# Contact Settings

contact:
  email: your@email.com # Add your form_id
  description: Akio comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
